libindy_vdr/src/ledger/identifiers/cred_def.rs, libindy_vdr/src/ledger/identifiers/rev_reg.rs, libindy_vdr/src/ledger/identifiers/schema.rs
Corrected behavior of `to_qualified` functions for public identificators. The previous implementation returned `schema:sov:schema:sov:did:sov:7ehexq99JSmcKrJKmydegi:2:gvt:1.0` for SchemaId and similar for others. 
Signed-off-by: artem.ivanov <artem.ivanov@dsr-company.com>
=> Corrected `to_qualified` function for identificators

Cargo.lock, README.md, indy-vdr-proxy/Cargo.toml, indy-vdr-proxy/src/app.rs, indy-vdr-proxy/src/handlers.rs, indy-vdr-proxy/src/main.rs
- Output HTML when text/html is requested or `?html` query string is used, otherwise output application/json and return timing information as a header (fixes #16)
- Add auto-refresh of validator pool. New `--refresh-interval` option, defaults to 120 minutes (fixes #17)
=> Update proxy response format, add pool auto-refresh

libindy_vdr/Cargo.toml, libindy_vdr/src/pool/types.rs, libindy_vdr/src/state_proof/node.rs, wrappers/python/indy_vdr/version.py
Ursa 0.3.7 was released with a different and incompatible version of the dependency, so this fixes a build error as well.
=> Import sha3 directly instead of through ursa

wrappers/python/demo/test.py, wrappers/python/indy_vdr/utils.py
Correctly use the networks folder as described in the spec: https://hyperledger.github.io/indy-did-method/#dynamic-using-github 
This should fix the failing test for the python wrapper
=> Correctly use the networks folder of the repository

libindy_vdr/src/resolver/did_document.rs
Fixes a bug that was taken over from the initial resolver prototype, see https://github.com/IDunion/indy-did-resolver/issues/26 for more details.
=> fix verkey expansion

libindy_vdr/src/pool/pool.rs
=> Skip verifiers with zero or negative node weights

wrappers/javascript/shared/src/indyVdr/IndyVdrRequest.ts
Small improvement to type response type inference for requests. Using the `infer` key we don't have to make the __responseType__ property public.
=> refactor(javascript): better response type inference

.github/workflows/build.yml, Cross.toml, build.sh
- Update to node16-compatible versions of actions
- Use cargo-cross to build linux binaries
- Add linux/arm64 build
- Use Python 3.8 over 3.6 for testing (3.6 is no longer easily available)
=> Update build actions

wrappers/javascript/indy-vdr-nodejs/package.json, wrappers/javascript/indy-vdr-react-native/package.json
There were some small issues with the JavaScript release. The publishing of the binaries fully worked 🎉
There's one issue before we can publish again and that is that the Indy VDR Shared package is already taken on NPM: https://www.npmjs.com/package/indy-vdr-shared. It's in security hold. I've submitted a request to Github/NPM to release the package and give us ownership. That can take weeks. I suggest we don't wait weeks, but maybe until next week. Otherwise we can use `@hyperledger` prefix for the package names.
=> build(javascript): fix some small release issues

libindy_vdr/src/ffi/ledger.rs, libindy_vdr/src/ledger/constants.rs, libindy_vdr/src/ledger/request_builder.rs, libindy_vdr/src/ledger/requests/ledgers_freeze.rs, libindy_vdr/src/ledger/requests/mod.rs, libindy_vdr/src/ledger/requests/pool.rs, libindy_vdr/tests/freeze_ledger.rs, libindy_vdr/tests/pool_config.rs, libindy_vdr/tests/pool_restart.rs, libindy_vdr/tests/pool_upgrade.rs, wrappers/python/demo/test.py, wrappers/python/indy_vdr/ledger.py
Here is the list of added functions:
```
build_node_request
build_pool_config
build_pool_restart
build_auth_rule_request
build_auth_rules_request
build_get_auth_rule_request
build_ledgers_freeze_request
build_get_frozen_ledgers_request 
```
These methods are needed for upgrading the Indy Test Automation repository to use Indy VDR for testing Indy Plenum and Indy Node instead of libindy.
This PR includes and depends on the changes from the PR https://github.com/hyperledger/indy-vdr/pull/134
=> Added missing reqeust builders into FFI and Python wrapper

wrappers/python/indy_vdr/ledger.py
Issue: Empty string (`""`) should be passed into Rust as is.  The previous condition passed `null` instead of empty string.
```
build_nym_request(did, did, None, None, "") - generated wrong request 
```
=> Corrected builder for NYM request in Python wrapper

wrappers/javascript/indy-vdr-shared/src/builder/GetCredentialDefinitionRequest.ts, wrappers/javascript/indy-vdr-shared/src/builder/GetSchemaRequest.ts
The found / not found responses were mixed up in the cred def response types
=> fix(js): cred def found/not found response type

wrappers/javascript/indy-vdr-react-native/cpp/indyVdr.cpp
Ticket https://github.com/hyperledger/indy-vdr/issues/204
=> Incorrect arguments order passing in buildGetAttribRequest

.github/workflows/build.yml, indy-vdr-proxy/Cargo.toml, wrappers/python/indy_vdr/ledger.py
Adds timezone.utc to datetime.combine to ensure time will be midnight in UTC regardless of the default timezone
=> Issue #210 InvalidClientTaaAcceptanceError time too precise error if container timezone is not UTC

wrappers/javascript/indy-vdr-nodejs/package.json, wrappers/javascript/yarn.lock
Following the issue with types that appeared in https://github.com/hyperledger/aries-askar/pull/170#issuecomment-1708337866, here we update patched `ref-napi` and `ffi-napi` to embed their own types instead of using the ones from the original ones.
=> fix(js): bump patched ref-napi/ffi-napi

indy-vdr-proxy/Cargo.toml, indy-vdr-proxy/src/main.rs, libindy_vdr/Cargo.toml, libindy_vdr/src/common/handle.rs, libindy_vdr/src/lib.rs, libindy_vdr/src/pool/manager.rs, libindy_vdr/src/pool/networker/zmq.rs, libindy_vdr/src/pool/types.rs, libindy_vdr/src/resolver/did_document.rs, libindy_vdr/src/utils/mod.rs, libindy_vdr/tests/utils/fixtures.rs
The functionality of indy-utils has been merged into indy-data-types in 0.7. This update includes the new versions of the ed25519/curve25519-dalek dependencies.
=> Update to indy-data-types 0.7; remove indy-utils

indy-vdr-proxy/src/handlers.rs, indy-vdr-proxy/src/main.rs, libindy_vdr/Cargo.toml, libindy_vdr/src/config/constants.rs, libindy_vdr/src/ffi/pool.rs, libindy_vdr/src/lib.rs, libindy_vdr/src/pool/genesis.rs, libindy_vdr/src/pool/handlers/catchup.rs, libindy_vdr/src/pool/handlers/consensus.rs, libindy_vdr/src/pool/handlers/full.rs, libindy_vdr/src/pool/handlers/mod.rs, libindy_vdr/src/pool/handlers/status.rs, libindy_vdr/src/pool/helpers.rs, libindy_vdr/src/pool/mod.rs, libindy_vdr/src/pool/requests/base.rs, libindy_vdr/src/pool/requests/mod.rs, libindy_vdr/src/pool/runner.rs, libindy_vdr/src/pool/types.rs, libindy_vdr/src/resolver/pool.rs, libindy_vdr/src/resolver/utils.rs, libindy_vdr/src/state_proof/mod.rs, libindy_vdr/src/utils/macros.rs, libindy_vdr/tests/utils/pool.rs
- Capture additional information about the state proof multi-signature verification.
- After performing a successful status request, prioritize the responding nodes when performing a subsequent catchup request. This helps to avoid delays waiting for nodes that are no longer active.
- Adjust default configuration parameters: ack_timeout -> 5 seconds, read timeout -> 30 seconds, connection request limit -> 10 requests.
=> Faster pool refresh

indy-vdr-proxy/src/handlers.rs, indy-vdr-proxy/src/main.rs, indy-vdr-proxy/src/utils.rs, libindy_vdr/src/common/error.rs, libindy_vdr/src/ffi/error.rs, libindy_vdr/src/ffi/mod.rs, libindy_vdr/src/ffi/pool.rs, libindy_vdr/src/ffi/resolver.rs, libindy_vdr/src/lib.rs, libindy_vdr/src/pool/builder.rs, libindy_vdr/src/pool/genesis.rs, libindy_vdr/src/pool/handlers/catchup.rs, libindy_vdr/src/pool/handlers/mod.rs, libindy_vdr/src/pool/handlers/status.rs, libindy_vdr/src/pool/helpers.rs, libindy_vdr/src/pool/manager.rs, libindy_vdr/src/pool/mod.rs, libindy_vdr/src/pool/runner.rs, libindy_vdr/src/pool/types.rs, libindy_vdr/tests/utils/pool.rs, wrappers/python/indy_vdr/__init__.py, wrappers/python/indy_vdr/bindings.py
This PR adds a new FFI method (and Python binding) to set the cache directory to use. When the cache directory is set, the library will automatically store the latest transactions for a given root hash and fetch them when creating a new pool. This means that as long as the same genesis transactions are passed in (via a string or file), it should be able to find the latest copy.
After the initial refresh of a pool, or if the transactions are cached, the library will also use a consensus `GET_TXN` request to check the latest pool state. This can be faster than the traditional status request as it will short-circuit after a single valid state proof, instead of attempting to contact all of the nodes.
=> Add genesis transactions caching

.github/workflows/build.yml, indy-vdr-proxy/Cargo.toml, wrappers/python/indy_vdr/version.py
The Python package is tested against the main branch of ACA-Py.
Due to a new release of the `home` crate, the cross installation on Android was failing. The CI install command is updated to use the lockfile in the cross repository.
=> Update python wrapper version to 0.4.1, proxy to 0.1.5

wrappers/javascript/indy-vdr-nodejs/package.json, wrappers/javascript/indy-vdr-react-native/package.json, wrappers/javascript/indy-vdr-shared/package.json, wrappers/javascript/lerna.json
Signed-off-by: Timo Glastra <timo@animo.id>
NOTE: this is to the js-0.4.1 branch and the release for JS wrapper must be created from that branch
=> fix: update to indy-vdr native binary 0.4.1

wrappers/javascript/indy-vdr-nodejs/package.json, wrappers/javascript/yarn.lock
Getting errors if this is not installed.
=> fix(js): add missing type

wrappers/javascript/indy-vdr-nodejs/package.json, wrappers/javascript/indy-vdr-react-native/cpp/indyVdr.cpp, wrappers/javascript/indy-vdr-react-native/package.json, wrappers/javascript/indy-vdr-react-native/src/NativeBindings.ts, wrappers/javascript/indy-vdr-shared/package.json, wrappers/javascript/lerna.json
Indy VDR does not allow a value of `0` to be passed, and the jsiToValue uses `0` as a default value if the value wasn't provided and it's optional. Same as is done in the Node.JS wrapper we convert the value to -1 (indicating it has no value).
=> fix(js): convert seqNo to -1 if 0

wrappers/javascript/lerna.json
Unfortunately, JS wrapper v0.2.2 could not be released due to a prettier error (CI didn't catch it before because PR to js-0.4.1 don't trigger lint task). So just fixing this to hopefully being able to release the new wrapper soon.
@TimoGlastra
=> style(js): fix formatting

wrappers/javascript/indy-vdr-react-native/android/build.gradle
This PR updates the react-native wrapper to get the minSdkVersion from the project config or fallback to the current hardcoded version. @TimoGlastra @berendsliedrecht
=> chore: update minSdkVersion to get the project version or fallback to 21

libindy_vdr/Cargo.toml, libindy_vdr/src/pool/cache/mod.rs, libindy_vdr/src/pool/cache/strategy.rs, libindy_vdr/src/pool/helpers.rs
the async_trait macro appeared to be crashing Bifold in react native. I've refactored the code to remove the `async_trait` macro and made some changes to the code to compensate
=> fix: fixed binary for react native

libindy_vdr/Cargo.toml
I think this should fix the mac build errors, though I'm still not sure why it's only happening on mac
=> Update Cargo.toml time package

libindy_vdr/Cargo.toml
This would fix issue #324 to allow compilation under rust 1.80+
=> Update Cargo.toml time crate

wrappers/python/indy_vdr/utils.py
And a minor usability improvement for the util to enable retrieving did:indy networks from a different repo than just the hyperledger one.
=> fix: point to hl indy-did-networks repo

libindy_vdr/Cargo.toml
Previously we were locked into time `=0.3.20`: https://github.com/hyperledger/indy-vdr/pull/166
Recently it was updated to `=0.3.36` due to issues with rust 1.80 and <0.3.36 versions of time.
However just as a crate cleanliness, it would be nice to only pin the version to 0.3.36 if we absolutely have to, dep conflicts may arise for consumers of the indy-vdr in the future as a result etc
FYI @andrewwhitehead : RE your [original decision](https://github.com/hyperledger/indy-vdr/pull/166) to lock the time version, is it still necessary?
=> Loosen time dependency patch version constraint 
