hyperledger/indy-vdr

- .tgitconfig
Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>
> Add TortoiseGit sign-off warning

- libindy_vdr/src/ffi/ledger.rs
- libindy_vdr/src/ledger/request_builder.rs
- libindy_vdr/src/ledger/requests/cred_def.rs
- libindy_vdr/src/ledger/requests/rev_reg.rs
- libindy_vdr/src/ledger/requests/rev_reg_def.rs
- libindy_vdr/src/ledger/requests/schema.rs
- wrappers/python/indy_vdr/ledger.py
- wrappers/python/indy_vdr/test.py
Also updates the signature of builder methods for schema, cred def, revocation methods.
> Add missing FFI methods for schemas, cred defs, revocation registries

- Cargo.lock
- indy-vdr-proxy/Cargo.toml
- indy-vdr-proxy/src/main.rs
> Add support for downloading genesis transaction files

- libindy_vdr/Cargo.toml
- libindy_vdr/src/ledger/request_builder.rs
- libindy_vdr/src/ledger/requests/rev_reg.rs
- libindy_vdr/src/lib.rs
This PR contains changes we need to integrate indy-vdr into Liibndy.
Here is the corresponding PR in Indy-SDK repository: https://github.com/hyperledger/indy-sdk/pull/2120
Signed-off-by: artem.ivanov <artem.ivanov@dsr-company.com>
> IS-1501:Libindy use Indy VDR

- libindy_vdr/src/lib.rs
- libindy_vdr/src/pool/handlers/consensus.rs
- libindy_vdr/src/pool/helpers.rs
- libindy_vdr/src/state_proof/mod.rs
Signed-off-by: artem.ivanov <artem.ivanov@dsr-company.com>
> IS-1516: Pluggable State proofs for Indy VDR

- libindy_vdr/src/ffi/ledger.rs
- libindy_vdr/src/ledger/constants.rs
- libindy_vdr/src/ledger/identifiers/mod.rs
- libindy_vdr/src/ledger/identifiers/rich_schema.rs
- libindy_vdr/src/ledger/request_builder.rs
- libindy_vdr/src/ledger/requests/mod.rs
- libindy_vdr/src/ledger/requests/rich_schema.rs
- wrappers/python/indy_vdr/ledger.py
- wrappers/python/indy_vdr/test.py
Signed-off-by: Andrew Nikitin <andrew.nikitin@dsr-corporation.com>
> [IS-1505] Skeleton for RichSchem building

- wrappers/python/indy_vdr/bindings.py
- wrappers/python/indy_vdr/ledger.py
Also fixes an issue with Python callbacks not being run because the async call could finish before the callback was registered.
> Fix python syntax error

- wrappers/golang/vdr/indy_vdr.go
Signed-off-by: kukgini <kukgini@gmail.com>
> fix type mismatch between golang and C

- Cargo.toml
- libindy_vdr/Cargo.toml
- libindy_vdr/src/ffi/error.rs
- libindy_vdr/src/ffi/mod.rs
- libindy_vdr/src/ffi/pool.rs
- libindy_vdr/src/ffi/requests.rs
- libindy_vdr/src/lib.rs
- libindy_vdr/tests/utils/constants.rs
- libindy_vdr/tests/utils/helpers.rs
- libindy_vdr/tests/utils/mod.rs
- wrappers/nodejs/test/unit/indy-vdr-utils.spec.ts
- wrappers/python/indy_vdr/version.py
Also switches from `lazy_static` to `once_cell`.
> Update indy-utils and related dependencies

- libindy_vdr/src/config/types.rs
- libindy_vdr/src/ffi/mod.rs
- libindy_vdr/src/ffi/pool.rs
- libindy_vdr/src/pool/networker/zmq.rs
- libindy_vdr/src/pool/pool.rs
- libindy_vdr/src/pool/requests/base.rs
- libindy_vdr/src/pool/runner.rs
- wrappers/golang/vdr/libindy_vdr.h
- wrappers/python/indy_vdr/bindings.py
- wrappers/python/indy_vdr/pool.py
> Support setting ZMQ socks proxy

- .github/workflows/build.yml
- README.md
- indy-vdr-proxy/Cargo.toml
- indy-vdr-proxy/src/main.rs
- libindy_vdr/Cargo.toml
- libindy_vdr/src/state_proof/node.rs
- libindy_vdr/src/utils/macros.rs
- wrappers/python/indy_vdr/version.py
- Updates dependencies
- Adds MacOS universal build for Python package
> 0.3.4 updates

- README.md
Fix of the doc to start indy vdr proxy with multiple ledgers flag.
Signed-off-by: Dominic Wörner <dom.woe@gmail.com>
> fix readme for indy-vdr-proxy

- .github/workflows/build.yml
- Cross.toml
Work funded by the Government of Ontario.
> build(android): add CI/CD

- .github/workflows/build.yml
- .gitignore
- wrappers/javascript/indy-vdr-nodejs/jest.config.ts
- wrappers/javascript/indy-vdr-react-native/android/CMakeLists.txt
- wrappers/javascript/indy-vdr-react-native/android/build.gradle
- wrappers/javascript/indy-vdr-react-native/indy-vdr.podspec
closes #115 
- Switched back to static libraries as there were some small issues with the dynamic libraries. We should change it in the future, but for now this will work (it is just a bit more megabytes that have to be downloaded).
- tested here https://www.npmjs.com/search?q=indy-vdr-test
- Supersedes #127 
Work funded by the Government of Ontario.
> Fixed minor issues with the build pipeline

- wrappers/javascript/indy-vdr-shared/src/builder/CredentialDefinitionRequest.ts
- wrappers/javascript/indy-vdr-shared/src/builder/SchemaRequest.ts
Fixes some minor typing issues
> fix(js): typing issues

- README.md
Signed-off-by: Stephen Curran <swcurran@gmail.com>
Signed-off-by: Stephen Curran <swcurran@cloudcompass.ca>
Signed-off-by: Stephen Curran <swcurran@gmail.com>
> Update README.md to update Rocketchat reference to Discord

- wrappers/javascript/indy-vdr-shared/src/builder/GetAcceptanceMechanismsRequest.ts
Signed-off-by: Timo Glastra <timo@animo.id>
> fix(js): aml response type

- libindy_vdr/Cargo.toml
- wrappers/javascript/indy-vdr-nodejs/package.json
- wrappers/javascript/indy-vdr-react-native/package.json
Work funded by the Government of Ontario.
> Updated the package version and download tag

- libindy_vdr/Cargo.toml
- wrappers/javascript/.eslintrc.js
- wrappers/javascript/indy-vdr-nodejs/package.json
- wrappers/javascript/indy-vdr-nodejs/scripts/arch.js
- wrappers/javascript/indy-vdr-react-native/package.json
- wrappers/javascript/indy-vdr-shared/package.json
- wrappers/python/indy_vdr/version.py
Work funded by the Government of Ontario.
> build: fix release pipeline

- .github/workflows/build.yml
- wrappers/javascript/indy-vdr-react-native/indy-vdr.podspec
> fix(js): framework path in podspec file

- wrappers/javascript/indy-vdr-nodejs/package.json
- wrappers/javascript/indy-vdr-react-native/package.json
- wrappers/javascript/indy-vdr-shared/package.json
- wrappers/javascript/indy-vdr-shared/src/indyVdr/IndyVdrRequest.ts
- wrappers/javascript/package.json
- wrappers/javascript/yarn.lock
Signed-off-by: Timo Glastra <timo@animo.id>
> fix(js): request type inference

- libindy_vdr/Cargo.toml
- wrappers/javascript/indy-vdr-nodejs/package.json
- wrappers/javascript/indy-vdr-react-native/package.json
- wrappers/javascript/indy-vdr-shared/package.json
- wrappers/javascript/lerna.json
- wrappers/python/indy_vdr/version.py
Signed-off-by: Timo Glastra <timo@animo.id>
> chore: update version to dev.4

- libindy_vdr/Cargo.toml
- wrappers/javascript/indy-vdr-nodejs/package.json
- wrappers/javascript/indy-vdr-react-native/package.json
- wrappers/javascript/indy-vdr-shared/package.json
- wrappers/javascript/lerna.json
- wrappers/python/indy_vdr/version.py
Signed-off-by: Artemkaaas <artem.ivanov@dsr-corporation.com>
> chore: update version to dev.5

- wrappers/javascript/.gitignore
- wrappers/javascript/indy-vdr-react-native/android/cpp-adapter.cpp
- wrappers/javascript/indy-vdr-react-native/cpp/HostObject.cpp
- wrappers/javascript/indy-vdr-react-native/cpp/HostObject.h
- wrappers/javascript/indy-vdr-react-native/cpp/indyVdr.cpp
- wrappers/javascript/indy-vdr-react-native/cpp/turboModuleUtility.cpp
- wrappers/javascript/indy-vdr-react-native/cpp/turboModuleUtility.h
- wrappers/javascript/indy-vdr-react-native/ios/IndyVdr.mm
> fix(js): allow multiple turbo modules to be registered

- .github/workflows/build.yml
- build-xcframework.sh
- wrappers/javascript/.gitignore
> build: add build xcframework script

- libindy_vdr/Cargo.toml
- wrappers/javascript/indy-vdr-nodejs/package.json
- wrappers/javascript/indy-vdr-react-native/package.json
- wrappers/javascript/indy-vdr-shared/package.json
- wrappers/javascript/lerna.json
> chore: version update

- build-xcframework.sh
Signed-off-by: Karim Stekelenburg <karim@animo.id>
> chore: fix path

- libindy_vdr/Cargo.toml
- wrappers/javascript/indy-vdr-nodejs/package.json
- wrappers/javascript/indy-vdr-react-native/package.json
- wrappers/javascript/indy-vdr-shared/package.json
- wrappers/javascript/lerna.json
> chore: update version

- .github/workflows/build.yml
- build-xcframework.sh
> build: do not include custom includes path

- wrappers/javascript/indy-vdr-react-native/cpp/HostObject.cpp
- wrappers/javascript/indy-vdr-react-native/cpp/turboModuleUtility.cpp
> fix(js): fixed some typos

- wrappers/javascript/indy-vdr-react-native/cpp/HostObject.cpp
- wrappers/javascript/indy-vdr-react-native/cpp/indyVdr.cpp
> fix(js): React Native use correct namespace

- wrappers/javascript/indy-vdr-react-native/cpp/turboModuleUtility.cpp
> fix(js): pass object to getError function

- libindy_vdr/include/libindy_vdr.h
- wrappers/javascript/indy-vdr-nodejs/src/NodeJSIndyVdr.ts
- wrappers/javascript/indy-vdr-nodejs/src/library/NativeBindings.ts
- wrappers/javascript/indy-vdr-nodejs/src/library/bindings.ts
- wrappers/javascript/indy-vdr-shared/src/builder/GetAttribRequest.ts
- wrappers/javascript/indy-vdr-shared/src/builder/GetNymRequest.ts
- wrappers/javascript/indy-vdr-shared/src/indyVdr/IndyVdrNativeBindings.ts
Re-generated the header file and adjusted the typescript calls for attrib/nym with the new parameters.
> quick fix for ffi bindings

- libindy_vdr/src/ledger/constants.rs
- libindy_vdr/src/ledger/request_builder.rs
- libindy_vdr/src/ledger/requests/flag.rs
- libindy_vdr/src/ledger/requests/mod.rs
- libindy_vdr/tests/flag.rs
Adds support to indy-vdr for config flag transactions. 
Supersedes #110
> Add support for config flag transactions

- wrappers/javascript/indy-vdr-nodejs/package.json
- wrappers/javascript/indy-vdr-nodejs/scripts/platform.js
> fix(nodejs): compatible with Windows builds

- wrappers/javascript/indy-vdr-nodejs/package.json
- wrappers/javascript/indy-vdr-react-native/package.json
- wrappers/javascript/indy-vdr-shared/package.json
- wrappers/javascript/lerna.json
Signed-off-by: Berend Sliedrecht <blu3beri@proton.me>
> chore(js): update to stable version

- libindy_vdr/src/ffi/ledger.rs
- libindy_vdr/src/ledger/constants.rs
- libindy_vdr/src/ledger/request_builder.rs
- libindy_vdr/src/ledger/requests/auth_rule.rs
- libindy_vdr/src/ledger/requests/nym.rs
- libindy_vdr/tests/auth_rule.rs
- libindy_vdr/tests/cred_def.rs
- libindy_vdr/tests/endorse_transaction.rs
- libindy_vdr/tests/flag.rs
- libindy_vdr/tests/nym.rs
- libindy_vdr/tests/resolver.rs
- libindy_vdr/tests/revoc_reg.rs
- libindy_vdr/tests/schema.rs
- libindy_vdr/tests/utils/helpers.rs
> Add enums for ledger role, ledger role update action

- indy-vdr-proxy/Cargo.toml
- indy-vdr-proxy/src/app.rs
- indy-vdr-proxy/src/main.rs
Adds optional TLS support using `tokio-rustls` for acceptor implementation and `rustls-pemfile` for parsing certificates.
> Support HTTPS

- .github/workflows/build.yml
- wrappers/javascript/indy-vdr-nodejs/README.md
- wrappers/javascript/indy-vdr-nodejs/package.json
- wrappers/javascript/indy-vdr-nodejs/src/ffi/alloc.ts
- wrappers/javascript/indy-vdr-nodejs/src/ffi/callback.ts
- wrappers/javascript/indy-vdr-nodejs/src/ffi/primitives.ts
- wrappers/javascript/indy-vdr-nodejs/src/ffi/serialize.ts
- wrappers/javascript/indy-vdr-nodejs/src/ffi/structures.ts
- wrappers/javascript/indy-vdr-nodejs/src/library/register.ts
- wrappers/javascript/package.json
- wrappers/javascript/yarn.lock
Similar approach as https://github.com/hyperledger/anoncreds-rs/pull/231 to make an easier set up in Node.js environment.
> fix(js)!: use patched ref-napi/ffi-napi for nodejs

- wrappers/javascript/lerna.json
Signed-off-by: Berend Sliedrecht <blu3beri@proton.me>
> make lerna look for the correct packages

- wrappers/javascript/indy-vdr-nodejs/package.json
- wrappers/javascript/indy-vdr-nodejs/scripts/install.js
- wrappers/javascript/indy-vdr-react-native/package.json
- wrappers/javascript/indy-vdr-shared/package.json
- wrappers/javascript/lerna.json
Signed-off-by: Berend Sliedrecht <blu3beri@proton.me>
> fix(js): use universal architecture for darwin

- wrappers/javascript/indy-vdr-nodejs/package.json
- wrappers/javascript/indy-vdr-react-native/package.json
- wrappers/javascript/indy-vdr-shared/package.json
- wrappers/javascript/lerna.json
Signed-off-by: Berend Sliedrecht <blu3beri@proton.me>
> update version for javascript wrapper

- wrappers/javascript/indy-vdr-shared/src/builder/RevocationRegistryEntryRequest.ts
- Updated the value of the delta to be compliant with a CL accumulator or any json.
according to: [anoncreds_clsignatures::RevocationRegistryDelta](https://github.com/hyperledger/anoncreds-clsignatures-rs/blob/b66dde993cb1e6d2f27fa0328d623c03b513834e/src/types.rs#L579)
> fix(js): type the revocation registry delta

- .github/workflows/build.yml
Same as https://github.com/hyperledger/anoncreds-rs/pull/296
> ci: allow to publish wrappers separately

- wrappers/javascript/indy-vdr-nodejs/package.json
- wrappers/javascript/indy-vdr-react-native/package.json
- wrappers/javascript/indy-vdr-shared/package.json
- wrappers/javascript/lerna.json
- wrappers/javascript/yarn.lock
This also adds the update of ffi-napi that was made to main
> chore: update wrapper to 0.2.2

- wrappers/javascript/indy-vdr-react-native/indy-vdr.podspec
Same fix as was done for Aries Askar here: https://github.com/hyperledger/aries-askar/pull/308
Signed-off-by: Stephen Curran <swcurran@gmail.com>
> feat: support react-native 0.75
